---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'This Cloudformation will create Cloudformation admin role, Exec role Master account'
Resources:
#---------------------------
#Create Required Resources(IAM)
#---------------------------
  IAMexecutionrole:
    DependsOn:
    - IAMAdminrole
    Type: AWS::IAM::Role
    Properties:
      RoleName: OrganizationAccountAccessRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: 
                AWS:
                - !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId',':root']]
            Action:
            - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess  
  IAMAdminrole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSCloudFormationStackSetAdministrationRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: 
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole    
      Policies: 
        - 
          PolicyName: 'sts-assume-for-stack-admin'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - 
                Effect: "Allow"
                Action:
                  - sts:AssumeRole
                Resource: "*"            