---
AWSTemplateFormatVersion: 2010-09-09
Description: "This Cloudformation will enable config, cloudwatch events and Alarm in Master Account"
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Masterdetail'
      Parameters:
      - MasterAccountNo
    - Label:
        default: 'Cloudtrail and Cloudwatch'
      Parameters:
      - CloudwatchLogGroupName
      - PrimaryEmailCloudwatchalarm
      - SecondaryEmailCloudwatchalarm
    - Label:
        default: 'Config Service'
      Parameters:
      - DeliveryFrequency
      - PrimaryEmailConfigservice
    ParameterLabels:
      MasterAccountNo:
        default: Master Account No
      CloudwatchLogGroupName:
        default: Cloudtrail logs Group Name in Cloudwatch
      PrimaryEmailCloudwatchalarm:
        default: Primary Email Address for Cloudwatch Alerts(Required)
      SecondaryEmailCloudwatchalarm:
        default: Secondary Email Address for Cloudwatch Alerts
      DeliveryFrequency:
        default: Config Service Snapshot Delivery Frequency
      PrimaryEmailConfigservice:
        default: Email Address for Config Service Notification        
Parameters:
  MasterAccountNo:
    Description: 'Master AWS Account No'
    Type: Number
    MinValue: 000000000001
    MaxValue: 999999999999
    ConstraintDescription: "Enter Master Account No Only Ex:- 012345678901"
  CloudwatchLogGroupName:
    Description: 'Name of Cloudwatch Log Group'
    Type: String
    Default: 'CloudTrail/DefaultLogGroup'
    MinLength: '0'
    MaxLength: '512'
    AllowedPattern: "[\\w-/.]+"
    ConstraintDescription: "Log group names in Master Account created by 3rd Cloudforamtion template"
  PrimaryEmailCloudwatchalarm:
    Type: String
    AllowedPattern: ".+@.+"
    Default: 'example@example.com'
    Description: "'Required'Triggered alarms will alert to this email address. Verification required and you can opt-out later. Make sure to validate otherwise you won't be able to delete the subscription and have to wait 3 days for automatic deletion."
  SecondaryEmailCloudwatchalarm:
    Type: String
    Description: 'Optional Secondary Email id.'
    AllowedPattern: ".+@.+"
    Default: 'example2@example.com'
    Description: "'Optional'Triggered alarms will alert to this email address. Verification required and you can opt-out later. Make sure to validate otherwise you won't be able to delete the subscription and have to wait 3 days for automatic deletion."
  DeliveryFrequency:
    Type: String
    Default: Six_Hours
    Description: "'Optional' The frequency with which AWS Config delivers configuration snapshots."
    AllowedValues:
      - One_Hour
      - Three_Hours
      - Six_Hours
      - Twelve_Hours
      - TwentyFour_Hours
  PrimaryEmailConfigservice:
    Type: String
    AllowedPattern: ".+@.+"
    Default: 'example@example.com'
    Description: "'Optional' Enter the email address you want to notify  stream change and notifications. ' this can cause a high volume of email.'"
Conditions:
  mastoraccount: !Equals [!Ref MasterAccountNo, '!Sub ${AWS::AccountId}']
  SecondarySubcription: !Not [!Equals [!Ref SecondaryEmailCloudwatchalarm, 'example2@example.com']]
  ConfigSubcription: !Not [!Equals [!Ref PrimaryEmailConfigservice, 'example@example.com']]
  ConfigServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSConfigServiceRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - config.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSConfigRole
      Policies:
      - PolicyName: CIS-configservice-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: AWSConfigRole
            Effect: Allow
            Action:
            - config:Put*
            Resource: '*'
          - Sid: AWSCloudTrailConfig
            Effect: Allow
            Action:
            - cloudtrail:List*
            - cloudtrail:Desc*
            - cloudtrail:Look*
            - cloudtrail:Get*
            Resource: '*'
          - Sid: AWSConfigPutObject
            Effect: Allow
            Action: s3:PutObject
            Resource:
            - !Join ['', ['arn:aws:s3:::','config-bucket12-',!Ref 'MasterAccountNo']]
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
          - Sid: AWSConfigGetObject
            Effect: Allow
            Action: s3:GetBucketAcl
            Resource:
            - !Join ['', ['arn:aws:s3:::',config-bucket12-, !Ref 'MasterAccountNo']]
  ConfigServiceSNS:
    Condition: ConfigSubcription
    Type: AWS::SNS::Subscription
    Properties:
        Endpoint: !Ref PrimaryEmailConfigservice
        Protocol: email
        TopicArn: !Ref 'ConfigTopic'
  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    DependsOn: 
    - ConfigServiceRole
    Properties:
      Name: myconfigservice-recorder
      RoleARN: !GetAtt  ConfigServiceRole.Arn
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: true
  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    DependsOn:
    - ConfigTopic
    Properties:
      Name: myconfigservice-deliverychannel
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: !Ref DeliveryFrequency
      S3BucketName: !Join ['', ['arn:aws:s3:::','config-bucket12-',!Ref MasterAccountNo]]
      SnsTopicARN: !Ref ConfigTopic